name: Deploy
on: [push, workflow_dispatch]
permissions: {contents: write}
jobs:
  build:
      runs-on: ubuntu-latest    steps:
            - uses: actions/checkout@v4
                  - uses: actions/setup-node@v4
                          with: {node-version: 20, cache: npm, cache-dependency-path: ./granzort/package-lock.json}
                                - run: |
                                          cd granzort
                                                    npm install
                                                              npm run build
                                                                    - uses: peaceiris/actions-gh-pages@v3
                                                                            with: {github_token: "${{ secrets.GITHUB_TOKEN }}", publish_dir: ./granzort/dist, destination_dir: granzort, keep_files: true}
                                                                            
